# Generated by Django 4.2.3 on 2023-07-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_loggers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="loggers",
            new_name="loggers2",
        ),
    ]
