# Generated by Django 4.2.3 on 2023-07-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_products_productimage"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
